# Pandas

## Basics

In [1]:
import numpy as np
import pandas as pd

### Dataframes

#### Series

In [2]:
list1 = [10, 20, 30]
dictionary = {1:10, 2:20, 3:30}
arr = np.array([10, 20, 30])
labels = ['a', 'b', 'c']

print(pd.Series(list1), '\n')
print(pd.Series(arr), '\n')
print(pd.Series(arr, labels), '\n')
print(pd.Series(dictionary))

0    10
1    20
2    30
dtype: int64 

0    10
1    20
2    30
dtype: int64 

a    10
b    20
c    30
dtype: int64 

1    10
2    20
3    30
dtype: int64


#### Creation of Dataframes

##### Using Dictionary

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,John,28,New York,65000
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


##### Using List

In [4]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df = pd.DataFrame(data_list)
print(df)
columns = ["Name","Age","City","Salary"]
df = pd.DataFrame(data_list,columns =columns)
df

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000


,Name,Age,City,Salary
0,John,28,New York,65000
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


##### Use of date_range() and index

In [5]:
dates = pd.date_range("20250120", periods=8)
df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=list("ABCD"))
df

,A,B,C,D
2025-01-20,0.409462,-0.313040,0.887126,0.105894
2025-01-21,0.270821,-0.020654,-0.669402,-1.519444
2025-01-22,-0.862873,-0.780969,-0.908434,-0.887471
2025-01-23,-0.980062,1.337074,0.886366,-0.232463
2025-01-24,-2.359379,-1.217172,-1.093280,-0.985946
2025-01-25,1.536000,2.393231,1.159499,0.759678
2025-01-26,0.072055,0.583324,-0.396296,1.016779
2025-01-27,-0.571320,0.209147,0.437801,-1.033544


#### Viewing Data

##### Header and Footer of Dataframe

In [ ]:
print(df.head(), '\n')
print(df.tail(3))

                   A         B         C         D
2025-01-20  0.409462 -0.313040  0.887126  0.105894
2025-01-21  0.270821 -0.020654 -0.669402 -1.519444
2025-01-22 -0.862873 -0.780969 -0.908434 -0.887471
2025-01-23 -0.980062  1.337074  0.886366 -0.232463
2025-01-24 -2.359379 -1.217172 -1.093280 -0.985946 

                   A         B         C         D
2025-01-25  1.536000  2.393231  1.159499  0.759678
2025-01-26  0.072055  0.583324 -0.396296  1.016779
2025-01-27 -0.571320  0.209147  0.437801 -1.033544


##### Information about Dataframe

In [ ]:
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes)

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27'],
              dtype='datetime64[us]', freq='D') 

Index(['A', 'B', 'C', 'D'], dtype='str') 

A    float64
B    float64
C    float64
D    float64
dtype: object


In [ ]:
print(df.info(), '\n')
print(df.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 8 entries, 2025-01-20 to 2025-01-27
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       8 non-null      float64
 1   B       8 non-null      float64
 2   C       8 non-null      float64
 3   D       8 non-null      float64
dtypes: float64(4)
memory usage: 320.0 bytes
None 

              A         B         C         D
count  8.000000  8.000000  8.000000  8.000000
mean  -0.310662  0.273868  0.037923 -0.347065
std    1.160760  1.164299  0.904189  0.914111
min   -2.359379 -1.217172 -1.093280 -1.519444
25%   -0.892171 -0.430022 -0.729160 -0.997846
50%   -0.249633  0.094246  0.020752 -0.559967
75%    0.305481  0.771761  0.886556  0.269340
max    1.536000  2.393231  1.159499  1.016779


##### Transformation of Dataframe

In [ ]:
print(df.T, '\n')
print(df.to_numpy())

   2025-01-20  2025-01-21  2025-01-22  2025-01-23  2025-01-24  2025-01-25  \
A    0.409462    0.270821   -0.862873   -0.980062   -2.359379    1.536000   
B   -0.313040   -0.020654   -0.780969    1.337074   -1.217172    2.393231   
C    0.887126   -0.669402   -0.908434    0.886366   -1.093280    1.159499   
D    0.105894   -1.519444   -0.887471   -0.232463   -0.985946    0.759678   

   2025-01-26  2025-01-27  
A    0.072055   -0.571320  
B    0.583324    0.209147  
C   -0.396296    0.437801  
D    1.016779   -1.033544   

[[ 0.40946243 -0.31304007  0.88712645  0.1058944 ]
 [ 0.27082109 -0.02065406 -0.66940212 -1.51944378]
 [-0.8628734  -0.78096868 -0.9084338  -0.88747056]
 [-0.98006244  1.33707352  0.88636611 -0.2324631 ]
 [-2.35937889 -1.21717167 -1.09327963 -0.98594644]
 [ 1.53599954  2.3932313   1.15949879  0.75967821]
 [ 0.07205461  0.58332358 -0.39629581  1.01677905]
 [-0.57131989  0.2091469   0.43780065 -1.03354443]]


##### Sorting in Dataframe

In [ ]:
df.sort_index(axis=1, ascending=False)

,D,C,B,A
2025-01-20,0.105894,0.887126,-0.313040,0.409462
2025-01-21,-1.519444,-0.669402,-0.020654,0.270821
2025-01-22,-0.887471,-0.908434,-0.780969,-0.862873
2025-01-23,-0.232463,0.886366,1.337074,-0.980062
2025-01-24,-0.985946,-1.093280,-1.217172,-2.359379
2025-01-25,0.759678,1.159499,2.393231,1.536000
2025-01-26,1.016779,-0.396296,0.583324,0.072055
2025-01-27,-1.033544,0.437801,0.209147,-0.571320


In [19]:
df.sort_values(by="B")

,A,B,C,D
2025-01-24,-2.359379,-1.217172,-1.093280,-0.985946
2025-01-22,-0.862873,-0.780969,-0.908434,-0.887471
2025-01-20,0.409462,-0.313040,0.887126,0.105894
2025-01-21,0.270821,-0.020654,-0.669402,-1.519444
2025-01-27,-0.571320,0.209147,0.437801,-1.033544
2025-01-26,0.072055,0.583324,-0.396296,1.016779
2025-01-23,-0.980062,1.337074,0.886366,-0.232463
2025-01-25,1.536000,2.393231,1.159499,0.759678


#### Selecting columns

In [7]:
print(df2["Name"])
df2[["Name", "City"]]

NameError: name 'df2' is not defined

#### Creating columns

In [ ]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2

,Name,Age,City,Salary,Designation
0,John,28,New York,65000,Doctor
1,Anna,34,Paris,70000,Eng.
2,Peter,29,Berlin,62000,Doctor
3,Linda,42,London,85000,Eng.


#### Removing columns

In [ ]:
df2.drop("Designation", axis=1, inplace=True) # If inplace is not set to True, the deletation will only be for current code not for memory.
df2

,Name,Age,City,Salary
0,John,28,New York,65000
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


#### Removing rows

In [ ]:
df2.drop(0, axis=0)

,Name,Age,City,Salary
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


In [ ]:
df2

,Name,Age,City,Salary
0,John,28,New York,65000
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


#### Selecting rows

In [ ]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df2.loc[[0,2]]

,Name,Age,City,Salary
0,John,28,New York,65000
2,Peter,29,Berlin,62000


In [ ]:
df2.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

In [ ]:
df2.loc[[1]]             # returns dataframe instead of a series

,Name,Age,City,Salary
1,Anna,34,Paris,70000


#### Selecting subsets of rows and columns

In [ ]:
df2.loc[[0,1]][['Name', 'City']]

,Name,City
0,John,New York
1,Anna,Paris


#### Conditional selection

In [ ]:
df2[df2['Age'] > 30]

,Name,Age,City,Salary
1,Anna,34,Paris,70000
3,Linda,42,London,85000


In [ ]:
df2[(df2["Age"] > 30) & (df2["City"] == "Paris")]

,Name,Age,City,Salary
1,Anna,34,Paris,70000


### Missing Data

#### Finding missing data

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,NaN
2,NaN,3,3.0,NaN
3,4.0,4,NaN,NaN
4,5.0,5,NaN,5.0


In [ ]:
df.isna()

,A,B,C,D
0,False,False,False,False
1,False,False,False,True
2,True,False,False,True
3,False,False,True,True
4,False,False,True,False


In [ ]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [ ]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [ ]:
df.dropna()

,A,B,C,D
0,1.0,1,1.0,1.0


In [ ]:
df.dropna(thresh=3)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,NaN
4,5.0,5,NaN,5.0


#### Filling missing data

In [ ]:
df.fillna(0)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,0.0
2,0.0,3,3.0,0.0
3,4.0,4,0.0,0.0
4,5.0,5,0.0,5.0


In [ ]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,400.0
2,0.0,3,3.0,400.0
3,4.0,4,300.0,400.0
4,5.0,5,300.0,5.0


### Merging, Concating, Joining Dataframes

#### Merging

In [ ]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [ ]:
employees

,employee_id,name,department
0,1,John,HR
1,2,Anna,IT
2,3,Peter,Finance
3,4,Linda,IT
4,5,Bob,HR


In [ ]:
salaries

,employee_id,salary,bonus
0,1,60000,5000
1,2,80000,10000
2,3,65000,7000
3,6,70000,8000
4,7,90000,12000


In [ ]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000,5000
1,2,Anna,IT,80000,10000
2,3,Peter,Finance,65000,7000


In [ ]:
pd.merge(employees, salaries, on='employee_id', how='outer')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000.0,5000.0
1,2,Anna,IT,80000.0,10000.0
2,3,Peter,Finance,65000.0,7000.0
3,4,Linda,IT,NaN,NaN
4,5,Bob,HR,NaN,NaN
5,6,NaN,NaN,70000.0,8000.0
6,7,NaN,NaN,90000.0,12000.0


In [ ]:
pd.merge(employees, salaries, on='employee_id', how='left')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000.0,5000.0
1,2,Anna,IT,80000.0,10000.0
2,3,Peter,Finance,65000.0,7000.0
3,4,Linda,IT,NaN,NaN
4,5,Bob,HR,NaN,NaN


In [ ]:
pd.merge(employees, salaries, on='employee_id', how='right')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000,5000
1,2,Anna,IT,80000,10000
2,3,Peter,Finance,65000,7000
3,6,NaN,NaN,70000,8000
4,7,NaN,NaN,90000,12000


#### Concating dataframes

In [ ]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [ ]:
df1

,A,B,C
0,A0,B0,C0
1,A1,B1,C1
2,A2,B2,C2


In [ ]:
df2

,A,B,C
0,A3,B3,C3
1,A4,B4,C4
2,A5,B5,C5


In [ ]:
pd.concat([df1, df2])

,A,B,C
0,A0,B0,C0
1,A1,B1,C1
2,A2,B2,C2
0,A3,B3,C3
1,A4,B4,C4
2,A5,B5,C5


In [ ]:
pd.concat([df1, df2], axis=1)

,A,B,C,A,B,C
0,A0,B0,C0,A3,B3,C3
1,A1,B1,C1,A4,B4,C4
2,A2,B2,C2,A5,B5,C5


#### Joining dataframes

In [ ]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [ ]:
df1

,name
1,Alice
2,Bob
3,Charlie


In [ ]:
df2

,score
2,85
3,90
4,75


In [ ]:
df1.join(df2)

,name,score
1,Alice,NaN
2,Bob,85.0
3,Charlie,90.0


In [ ]:
df1.join(df2, how='outer')

,name,score
1,Alice,NaN
2,Bob,85.0
3,Charlie,90.0
4,NaN,75.0


### Group by & Aggregation

#### Group by

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

,Category,Store,Sales,Quantity,Date
0,A,S1,100,10,2023-01-01
1,B,S1,200,15,2023-01-02
2,A,S2,150,12,2023-01-03
3,B,S2,250,18,2023-01-04
4,A,S1,120,8,2023-01-05
5,B,S2,180,20,2023-01-06
6,A,S2,200,15,2023-01-07
7,B,S1,300,25,2023-01-08


In [ ]:
cat_group = df.groupby('Category')             # Object
cat_group

In [ ]:
cat_group = df.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
store_group = df.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
combine_group = df.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

#### Aggregation

In [ ]:
df['Sales'].mean()

np.float64(187.5)

In [ ]:
df['Sales'].sum()

np.int64(1500)

In [ ]:
df['Sales'].min()

np.int64(100)

In [ ]:
df['Sales'].max()

np.int64(300)

In [ ]:
df['Sales'].count()

np.int64(8)

In [ ]:
df['Sales'].std()

np.float64(66.06274074155351)

In [ ]:
df['Sales'].median()

np.float64(190.0)

In [ ]:
df['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean       187.500000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

### Pivot Tables and Crosstabs

#### Pivot tables

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

,Date,Product,Region,Sales,Units,Rep,Month,Quarter
0,2023-01-01,A,East,327,49,John,January,Q1
1,2023-01-02,B,West,272,16,Mary,January,Q1
2,2023-01-03,C,North,639,54,Bob,January,Q1
3,2023-01-04,D,South,335,90,Alice,January,Q1
4,2023-01-05,A,East,348,43,John,January,Q1
5,2023-01-06,B,West,224,11,Mary,January,Q1
6,2023-01-07,C,North,674,35,Bob,January,Q1
7,2023-01-08,D,South,590,31,Alice,January,Q1
8,2023-01-09,A,East,752,16,John,January,Q1
9,2023-01-10,B,West,759,69,Mary,January,Q1


In [ ]:
pivot_table_1 = pd.pivot_table(data=df, values='Sales', index='Region', columns='Product')
pivot_table_1

Product,A,B,C,D
Region,,,,
East,405.6,NaN,NaN,NaN
North,NaN,NaN,639.6,NaN
South,NaN,NaN,NaN,490.2
West,NaN,403.4,NaN,NaN


In [ ]:
pivot_table_2 = pd.pivot_table(data=df, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

Sales                      Units                  
Product      A      B      C      D     A     B     C     D
Region                                                     
East     405.6    NaN    NaN    NaN  57.6   NaN   NaN   NaN
North      NaN    NaN  639.6    NaN   NaN   NaN  59.8   NaN
South      NaN    NaN    NaN  490.2   NaN   NaN   NaN  55.8
West       NaN  403.4    NaN    NaN   NaN  50.4   NaN   NaN

#### Crosstabs

In [ ]:
crosstab_1 = pd.crosstab(df['Region'], df['Product'])
crosstab_1

Product,A,B,C,D
Region,,,,
East,5,0,0,0
North,0,0,5,0
South,0,0,0,5
West,0,5,0,0


### Operations

#### Dataframes basic operations

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

,A,B,C
0,1,10,100
1,2,20,200
2,3,30,300
3,4,40,400
4,5,50,500


In [ ]:
df1.shape

(5, 3)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes


In [ ]:
df1.describe()

,A,B,C
count,5.000000,5.000000,5.000000
mean,3.000000,30.000000,300.000000
std,1.581139,15.811388,158.113883
min,1.000000,10.000000,100.000000
25%,2.000000,20.000000,200.000000
50%,3.000000,30.000000,300.000000
75%,4.000000,40.000000,400.000000
max,5.000000,50.000000,500.000000


In [ ]:
df2 = df1['A'] + 10
df2

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

#### Applying functions

In [ ]:
def square(x):
    return x**2

In [ ]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
df1['D'] = df1['B'].apply(square)
df1

,A,B,C,D
0,1,10,100,100
1,2,20,200,400
2,3,30,300,900
3,4,40,400,1600
4,5,50,500,2500


In [ ]:
df1['E'] = df1['A'].apply(lambda x: x**3)
df1

,A,B,C,D,E
0,1,10,100,100,1
1,2,20,200,400,8
2,3,30,300,900,27
3,4,40,400,1600,64
4,5,50,500,2500,125
