# Pandas

## Basics

In [388]:
import numpy as np
import pandas as pd

### Dataframes

#### Series

In [389]:
list1 = [10, 20, 30]
dictionary = {1:10, 2:20, 3:30}
arr = np.array([10, 20, 30])
labels = ['a', 'b', 'c']

print(pd.Series(list1), '\n')
print(pd.Series(arr), '\n')
print(pd.Series(arr, labels), '\n')
print(pd.Series(dictionary))

0    10
1    20
2    30
dtype: int64 

0    10
1    20
2    30
dtype: int64 

a    10
b    20
c    30
dtype: int64 

1    10
2    20
3    30
dtype: int64


#### Creation of Dataframes

##### Using Dictionary

In [390]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

,Name,Age,City,Salary
0,John,28,New York,65000
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


##### Using List

In [391]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
print(df2)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =columns)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000


,Name,Age,City,Salary
0,John,28,New York,65000
1,Anna,34,Paris,70000
2,Peter,29,Berlin,62000
3,Linda,42,London,85000


##### Use of date_range() and index

In [392]:
dates = pd.date_range("2025-01-20", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

,A,B,C,D
2025-01-20,1.645993,1.664105,2.230535,1.325488
2025-01-21,1.739255,-1.957326,-1.914762,-0.190737
2025-01-22,0.169724,-1.097761,0.881538,-0.822820
2025-01-23,0.005714,1.219545,-0.116482,-0.094631
2025-01-24,-0.002937,-0.099620,-0.102327,0.236371
2025-01-25,-0.259521,1.262838,1.414356,-0.671190


#### Viewing Data

##### Header and Footer of Dataframe

In [393]:
print(df.head(), '\n')
print(df.tail(3))

                   A         B         C         D
2025-01-20  1.645993  1.664105  2.230535  1.325488
2025-01-21  1.739255 -1.957326 -1.914762 -0.190737
2025-01-22  0.169724 -1.097761  0.881538 -0.822820
2025-01-23  0.005714  1.219545 -0.116482 -0.094631
2025-01-24 -0.002937 -0.099620 -0.102327  0.236371 

                   A         B         C         D
2025-01-23  0.005714  1.219545 -0.116482 -0.094631
2025-01-24 -0.002937 -0.099620 -0.102327  0.236371
2025-01-25 -0.259521  1.262838  1.414356 -0.671190


##### Information about Dataframe

In [394]:
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes)

DatetimeIndex(['2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23',
               '2025-01-24', '2025-01-25'],
              dtype='datetime64[us]', freq='D') 

Index(['A', 'B', 'C', 'D'], dtype='str') 

A    float64
B    float64
C    float64
D    float64
dtype: object


In [395]:
print(df.info(), '\n')
print(df.describe())

<class 'pandas.DataFrame'>
DatetimeIndex: 6 entries, 2025-01-20 to 2025-01-25
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes
None 

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.549705  0.165297  0.398810 -0.036253
std    0.896376  1.465161  1.448368  0.771721
min   -0.259521 -1.957326 -1.914762 -0.822820
25%   -0.000774 -0.848226 -0.112943 -0.551077
50%    0.087719  0.559962  0.389606 -0.142684
75%    1.276926  1.252015  1.281151  0.153620
max    1.739255  1.664105  2.230535  1.325488


##### Transformation of Dataframe

In [396]:
print(df.T, '\n')
print(df.to_numpy())

   2025-01-20  2025-01-21  2025-01-22  2025-01-23  2025-01-24  2025-01-25
A    1.645993    1.739255    0.169724    0.005714   -0.002937   -0.259521
B    1.664105   -1.957326   -1.097761    1.219545   -0.099620    1.262838
C    2.230535   -1.914762    0.881538   -0.116482   -0.102327    1.414356
D    1.325488   -0.190737   -0.822820   -0.094631    0.236371   -0.671190 

[[ 1.64599346  1.66410542  2.23053517  1.32548823]
 [ 1.7392552  -1.95732587 -1.91476187 -0.19073731]
 [ 0.16972401 -1.09776098  0.88153806 -0.82282001]
 [ 0.00571368  1.21954502 -0.11648183 -0.09463142]
 [-0.00293657 -0.09962007 -0.10232678  0.2363707 ]
 [-0.25952087  1.26283803  1.41435588 -0.67118971]]


##### Sorting in Dataframe

In [397]:
df.sort_index(axis=1, ascending=False)

,D,C,B,A
2025-01-20,1.325488,2.230535,1.664105,1.645993
2025-01-21,-0.190737,-1.914762,-1.957326,1.739255
2025-01-22,-0.822820,0.881538,-1.097761,0.169724
2025-01-23,-0.094631,-0.116482,1.219545,0.005714
2025-01-24,0.236371,-0.102327,-0.099620,-0.002937
2025-01-25,-0.671190,1.414356,1.262838,-0.259521


In [398]:
df.sort_values(by="B")

,A,B,C,D
2025-01-21,1.739255,-1.957326,-1.914762,-0.190737
2025-01-22,0.169724,-1.097761,0.881538,-0.822820
2025-01-24,-0.002937,-0.099620,-0.102327,0.236371
2025-01-23,0.005714,1.219545,-0.116482,-0.094631
2025-01-25,-0.259521,1.262838,1.414356,-0.671190
2025-01-20,1.645993,1.664105,2.230535,1.325488


### Selection

##### Getitem ([])

In [399]:
# Column
df['A']

2025-01-20    1.645993
2025-01-21    1.739255
2025-01-22    0.169724
2025-01-23    0.005714
2025-01-24   -0.002937
2025-01-25   -0.259521
Freq: D, Name: A, dtype: float64

In [400]:
# Multiple columns
df[['A', 'B']]

,A,B
2025-01-20,1.645993,1.664105
2025-01-21,1.739255,-1.957326
2025-01-22,0.169724,-1.097761
2025-01-23,0.005714,1.219545
2025-01-24,-0.002937,-0.099620
2025-01-25,-0.259521,1.262838


In [401]:
# rows
df[0:3]

,A,B,C,D
2025-01-20,1.645993,1.664105,2.230535,1.325488
2025-01-21,1.739255,-1.957326,-1.914762,-0.190737
2025-01-22,0.169724,-1.097761,0.881538,-0.822820


##### Selection by label

In [402]:
# row
df.loc[dates[0]]

A    1.645993
B    1.664105
C    2.230535
D    1.325488
Name: 2025-01-20 00:00:00, dtype: float64

In [403]:
# all rows with only 'A' and 'B' column
df.loc[:, ['A', 'B']]

,A,B
2025-01-20,1.645993,1.664105
2025-01-21,1.739255,-1.957326
2025-01-22,0.169724,-1.097761
2025-01-23,0.005714,1.219545
2025-01-24,-0.002937,-0.099620
2025-01-25,-0.259521,1.262838


In [404]:
# subset of selected rows and columns
df.loc['2025-01-22':'2025-01-25', ['A', 'B']]

,A,B
2025-01-22,0.169724,-1.097761
2025-01-23,0.005714,1.219545
2025-01-24,-0.002937,-0.099620
2025-01-25,-0.259521,1.262838


In [405]:
# Single element
print(df.loc[dates[0], 'A'])
print(df.at[dates[0], 'A'])

1.6459934629430022
1.6459934629430022


##### Selection by position

In [406]:
# row
df.iloc[2]

A    0.169724
B   -1.097761
C    0.881538
D   -0.822820
Name: 2025-01-22 00:00:00, dtype: float64

In [407]:
# subset
df.iloc[1:3, :2]

,A,B
2025-01-21,1.739255,-1.957326
2025-01-22,0.169724,-1.097761


In [408]:
# list of integer position locations
df.iloc[[1, 2, 4], [1, 3]]

,B,D
2025-01-21,-1.957326,-0.190737
2025-01-22,-1.097761,-0.822820
2025-01-24,-0.099620,0.236371


In [409]:
# Single element
print(df.iloc[1, 2])
print(df.iat[1, 2])

-1.9147618710367615
-1.9147618710367615


##### Boolean indexing

In [410]:
#Select rows where df.A is greater than 0.
df[df['A'] > 0]

,A,B,C,D
2025-01-20,1.645993,1.664105,2.230535,1.325488
2025-01-21,1.739255,-1.957326,-1.914762,-0.190737
2025-01-22,0.169724,-1.097761,0.881538,-0.822820
2025-01-23,0.005714,1.219545,-0.116482,-0.094631


In [411]:
#Selecting values from a DataFrame where a boolean condition is met:
df[df > 0]

,A,B,C,D
2025-01-20,1.645993,1.664105,2.230535,1.325488
2025-01-21,1.739255,NaN,NaN,NaN
2025-01-22,0.169724,NaN,0.881538,NaN
2025-01-23,0.005714,1.219545,NaN,NaN
2025-01-24,NaN,NaN,NaN,0.236371
2025-01-25,NaN,1.262838,1.414356,NaN


### Setting

##### Setting new column

In [412]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('2025-01-20', periods=6))
df['F'] = s1
df.head(3)

,A,B,C,D,F
2025-01-20,1.645993,1.664105,2.230535,1.325488,1
2025-01-21,1.739255,-1.957326,-1.914762,-0.190737,2
2025-01-22,0.169724,-1.097761,0.881538,-0.822820,3


##### Modifying column

In [413]:
df['D'] = np.array([5] * len(df))
df.head(3)

,A,B,C,D,F
2025-01-20,1.645993,1.664105,2.230535,5,1
2025-01-21,1.739255,-1.957326,-1.914762,5,2
2025-01-22,0.169724,-1.097761,0.881538,5,3


##### Setting new element

In [414]:
df.at[dates[0], 'A'] = 0
df.iat[0, 1] = 0
df.iloc[0]

A    0.000000
B    0.000000
C    2.230535
D    5.000000
F    1.000000
Name: 2025-01-20 00:00:00, dtype: float64

##### Setting new row

In [415]:
df.loc[pd.Timestamp('2025-01-29')] = np.append(np.random.randn(3), [5, 7])
df.tail(3)
# You can modify row like this also.

,A,B,C,D,F
2025-01-24,-0.002937,-0.099620,-0.102327,5.0,5.0
2025-01-25,-0.259521,1.262838,1.414356,5.0,6.0
2025-01-29,-1.495133,1.959827,0.064863,5.0,7.0


##### Modifying the index of row

In [416]:
df.rename(index={pd.Timestamp('2025-01-29'): pd.Timestamp('2025-01-26')}, inplace=True)
df.tail(3)

,A,B,C,D,F
2025-01-24,-0.002937,-0.099620,-0.102327,5.0,5.0
2025-01-25,-0.259521,1.262838,1.414356,5.0,6.0
2025-01-26,-1.495133,1.959827,0.064863,5.0,7.0


##### Removing column

In [417]:
df.drop('A', axis=1).head(3)

# df.drop('A', axis=1, inplace=True) will delete it permanently from memory.

,B,C,D,F
2025-01-20,0.000000,2.230535,5.0,1.0
2025-01-21,-1.957326,-1.914762,5.0,2.0
2025-01-22,-1.097761,0.881538,5.0,3.0


##### Removing row

In [418]:
df.drop('2025-01-24')

,A,B,C,D,F
2025-01-20,0.000000,0.000000,2.230535,5.0,1.0
2025-01-21,1.739255,-1.957326,-1.914762,5.0,2.0
2025-01-22,0.169724,-1.097761,0.881538,5.0,3.0
2025-01-23,0.005714,1.219545,-0.116482,5.0,4.0
2025-01-25,-0.259521,1.262838,1.414356,5.0,6.0
2025-01-26,-1.495133,1.959827,0.064863,5.0,7.0


### Missing Data

#### Finding missing data

In [419]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df2 = pd.DataFrame(data)
df2

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,NaN
2,NaN,3,3.0,NaN
3,4.0,4,NaN,NaN
4,5.0,5,NaN,5.0


In [420]:
df2.isna()

,A,B,C,D
0,False,False,False,False
1,False,False,False,True
2,True,False,False,True
3,False,False,True,True
4,False,False,True,False


In [421]:
df2.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [422]:
df2.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

#### Removing missing data

In [423]:
df2.dropna()

,A,B,C,D
0,1.0,1,1.0,1.0


In [424]:
df2.dropna(thresh=3)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,NaN
4,5.0,5,NaN,5.0


#### Filling missing data

In [425]:
df2.fillna(0)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,0.0
2,0.0,3,3.0,0.0
3,4.0,4,0.0,0.0
4,5.0,5,0.0,5.0


In [426]:
values = {'A':0,'B':100,"C":300,'D':400}
df2.fillna(value=values)

,A,B,C,D
0,1.0,1,1.0,1.0
1,2.0,2,2.0,400.0
2,0.0,3,3.0,400.0
3,4.0,4,300.0,400.0
4,5.0,5,300.0,5.0


### Merge and Grouping

#### Merging

In [427]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [428]:
employees

,employee_id,name,department
0,1,John,HR
1,2,Anna,IT
2,3,Peter,Finance
3,4,Linda,IT
4,5,Bob,HR


In [429]:
salaries

,employee_id,salary,bonus
0,1,60000,5000
1,2,80000,10000
2,3,65000,7000
3,6,70000,8000
4,7,90000,12000


In [430]:
pd.merge(employees, salaries)             # pd.merge(employees, salaries, on='employee_id', how='inner')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000,5000
1,2,Anna,IT,80000,10000
2,3,Peter,Finance,65000,7000


In [431]:
pd.merge(employees, salaries, on='employee_id', how='outer')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000.0,5000.0
1,2,Anna,IT,80000.0,10000.0
2,3,Peter,Finance,65000.0,7000.0
3,4,Linda,IT,NaN,NaN
4,5,Bob,HR,NaN,NaN
5,6,NaN,NaN,70000.0,8000.0
6,7,NaN,NaN,90000.0,12000.0


In [432]:
pd.merge(employees, salaries, on='employee_id', how='left')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000.0,5000.0
1,2,Anna,IT,80000.0,10000.0
2,3,Peter,Finance,65000.0,7000.0
3,4,Linda,IT,NaN,NaN
4,5,Bob,HR,NaN,NaN


In [433]:
pd.merge(employees, salaries, on='employee_id', how='right')

,employee_id,name,department,salary,bonus
0,1,John,HR,60000,5000
1,2,Anna,IT,80000,10000
2,3,Peter,Finance,65000,7000
3,6,NaN,NaN,70000,8000
4,7,NaN,NaN,90000,12000


#### Concating

In [434]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [435]:
df1

,A,B,C
0,A0,B0,C0
1,A1,B1,C1
2,A2,B2,C2


In [436]:
df2

,A,B,C
0,A3,B3,C3
1,A4,B4,C4
2,A5,B5,C5


In [437]:
pd.concat([df1, df2])

,A,B,C
0,A0,B0,C0
1,A1,B1,C1
2,A2,B2,C2
0,A3,B3,C3
1,A4,B4,C4
2,A5,B5,C5


In [438]:
pd.concat([df1, df2], axis=1)

,A,B,C,A,B,C
0,A0,B0,C0,A3,B3,C3
1,A1,B1,C1,A4,B4,C4
2,A2,B2,C2,A5,B5,C5


#### Joining

In [439]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

print(df1, df2, sep='\n\n')

      name
1    Alice
2      Bob
3  Charlie

   score
2     85
3     90
4     75


In [440]:
df1.join(df2)

,name,score
1,Alice,NaN
2,Bob,85.0
3,Charlie,90.0


In [441]:
df1.join(df2, how='outer')

,name,score
1,Alice,NaN
2,Bob,85.0
3,Charlie,90.0
4,NaN,75.0


#### Grouping

In [442]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df2 = pd.DataFrame(data)
df2

,Category,Store,Sales,Quantity,Date
0,A,S1,100,10,2023-01-01
1,B,S1,200,15,2023-01-02
2,A,S2,150,12,2023-01-03
3,B,S2,250,18,2023-01-04
4,A,S1,120,8,2023-01-05
5,B,S2,180,20,2023-01-06
6,A,S2,200,15,2023-01-07
7,B,S1,300,25,2023-01-08


In [443]:
cat_group = df2.groupby('Category')
cat_group

In [444]:
cat_group = df2.groupby('Category')['Sales'].sum()
cat_group

Category
A    570
B    930
Name: Sales, dtype: int64

In [445]:
store_group = df2.groupby('Store')['Sales'].sum()
store_group

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [446]:
combine_group = df2.groupby(['Category', 'Store'])['Sales'].sum()
combine_group

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

### Stack and Pivot Tables

#### Pivot tables

In [447]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df2 = pd.DataFrame(data)

df2['Month'] = df2['Date'].dt.month_name()
df2['Quarter'] = 'Q' + df2['Date'].dt.quarter.astype(str)
df2

,Date,Product,Region,Sales,Units,Rep,Month,Quarter
0,2023-01-01,A,East,261,13,John,January,Q1
1,2023-01-02,B,West,229,27,Mary,January,Q1
2,2023-01-03,C,North,876,39,Bob,January,Q1
3,2023-01-04,D,South,336,54,Alice,January,Q1
4,2023-01-05,A,East,104,24,John,January,Q1
5,2023-01-06,B,West,967,54,Mary,January,Q1
6,2023-01-07,C,North,236,57,Bob,January,Q1
7,2023-01-08,D,South,753,10,Alice,January,Q1
8,2023-01-09,A,East,705,90,John,January,Q1
9,2023-01-10,B,West,271,75,Mary,January,Q1


In [448]:
pivot_table_1 = pd.pivot_table(data=df2, values='Sales', index='Region', columns='Product')
pivot_table_1

Product,A,B,C,D
Region,,,,
East,369.0,NaN,NaN,NaN
North,NaN,NaN,426.0,NaN
South,NaN,NaN,NaN,623.6
West,NaN,398.8,NaN,NaN


In [449]:
pivot_table_2 = pd.pivot_table(data=df2, values=['Sales', 'Units'], index='Region', columns='Product')
pivot_table_2

Sales                      Units                  
Product      A      B      C      D     A     B     C     D
Region                                                     
East     369.0    NaN    NaN    NaN  40.6   NaN   NaN   NaN
North      NaN    NaN  426.0    NaN   NaN   NaN  53.4   NaN
South      NaN    NaN    NaN  623.6   NaN   NaN   NaN  46.2
West       NaN  398.8    NaN    NaN   NaN  55.8   NaN   NaN

#### Crosstabs

In [450]:
crosstab_1 = pd.crosstab(df2['Region'], df2['Product'])
crosstab_1

Product,A,B,C,D
Region,,,,
East,5,0,0,0
North,0,0,5,0
South,0,0,0,5
West,0,5,0,0


### Operations

#### Dataframes basic operations

##### Aggregation functions

In [451]:
df1 = pd.DataFrame({
    'Id': [1, 2, 3, 4, 5],
    'Price': [600, 720, 590, 650, 700],
    'Sales': [1000, 1000, 1200, 900, 1000]
})
df1

,Id,Price,Sales
0,1,600,1000
1,2,720,1000
2,3,590,1200
3,4,650,900
4,5,700,1000


In [452]:
print('Mean : ', df1['Sales'].mean())
print('Sum : ', df1['Sales'].sum())
print('Min : ', df1['Sales'].min())
print('Max : ', df1['Sales'].max())
print('Count : ', df1['Sales'].count())
print('Std : ', df1['Sales'].std())
print('Median : ', df1['Sales'].median())

Mean :  1020.0
Sum :  5100
Min :  900
Max :  1200
Count :  5
Std :  109.54451150103323
Median :  1000.0


In [453]:
df1['Sales'].agg(['mean', 'min', 'max', 'sum', 'count', 'std', 'median'])

mean      1020.000000
min        900.000000
max       1200.000000
sum       5100.000000
count        5.000000
std        109.544512
median    1000.000000
Name: Sales, dtype: float64

##### Basic Operations

In [454]:
df2 = df1['Id'] + 10
df2

0    11
1    12
2    13
3    14
4    15
Name: Id, dtype: int64

#### Applying functions

In [455]:
def square(x):
    return x**2

In [456]:
df1['Id'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: Id, dtype: int64

In [457]:
df1['raw Id'] = df1['Id'].apply(lambda x: x**3)
df1

,Id,Price,Sales,raw Id
0,1,600,1000,1
1,2,720,1000,8
2,3,590,1200,27
3,4,650,900,64
4,5,700,1000,125
