# Numpy

## Advanced

In [40]:
import numpy as np

### Triogonometric Functions

#### Basic Functions

In [41]:
angle = np.pi / 2
print(np.sin(angle))             # Angle in radian
print(np.cos(angle))
print(np.tan(angle))

1.0
6.123233995736766e-17
1.633123935319537e+16


#### For Arrays

In [42]:
angles = np.array([0, np.pi / 2, np.pi])

print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#### Conversion between degrees & radians

In [43]:
print(np.deg2rad(90))
print(np.rad2deg(np.pi))

1.5707963267948966
180.0


#### Inverse Functions

In [44]:
inverse_angle = 1

print(np.arcsin(inverse_angle))
print(np.arccos(inverse_angle))
print(np.arctan(inverse_angle))

1.5707963267948966
0.0
0.7853981633974483


#### Hyperbolic Functions

In [45]:
print(np.sinh(angle))
print(np.cosh(angle))
print(np.tanh(angle))

print(np.arcsinh(inverse_angle))
print(np.arccosh(inverse_angle))
print(np.arctanh(inverse_angle - 0.1))

2.3012989023072947
2.5091784786580567
0.9171523356672744
0.881373587019543
0.0
1.4722194895832204


### Useful Functions

#### exp

In [46]:
print(np.exp(0))              # Returns exponential value
print(np.exp(1))
print(np.exp(2))

print(np.expm1(0))            # Return e**x - 1
print(np.expm1(1))
print(np.expm1(2))

1.0
2.718281828459045
7.38905609893065
0.0
1.718281828459045
6.38905609893065


In [47]:
arr = np.array([1,2,3,4,5])
print(np.exp(arr))
print(np.expm1(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]


#### log

In [48]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


#### fromfunction

This numpy array creation method applies the given function to all the elements while creating the array.

##### Using def

In [49]:
def sum(x, y):
    return x + y

arr = np.fromfunction(sum, (3, 5), dtype=int)
arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

##### Using lambda

In [50]:
arr = np.fromfunction(lambda x, y: (x+1) * (y+1), (4, 4), dtype=int)
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

#### flat

In [51]:
arr = np.arange(1,11)
for i in arr.flat:               # This lets you to work with each elements indivisually of numpy array.
    print(i)

1
2
3
4
5
6
7
8
9
10


### ellipsis (...)

#### 3D array

In [52]:
arr_3D = np.arange(2*3*4).reshape(2,3,4)

print(arr_3D[:, :, 2])
print()
print(arr_3D[..., 2])

[[ 2  6 10]
 [14 18 22]]

[[ 2  6 10]
 [14 18 22]]


#### 4D array

In [53]:
arr_4D = np.arange(2*3*4*5).reshape(2,3,4,5)

print(arr_4D[0, :, :, 2])
print()
print(arr_4D[0, ..., 2])

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


### -1 in reshaping

In [54]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
arr.reshape(4, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
arr_3D.reshape(2, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [57]:
arr_3D.reshape(4, -1)            # Converted from 3D to 2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### I/O in Numpy

#### Reading from files

##### Creating array using file data

In [58]:
# genfromtxt will convert file's data to numpy array.
arr = np.genfromtxt("files/numbers_1.txt")
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [59]:
# delimeter defines which seperator is used in file.
arr = np.genfromtxt("files/numbers_2.csv", delimiter=",")
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

##### Datatype

In [60]:
# dtype converts datatype to given datatype.
# Default datatype is float
arr = np.genfromtxt("files/numbers_1.txt", delimiter=",", dtype=int)
print(arr)
arr = np.genfromtxt("files/numbers_1.txt", delimiter=",", dtype=str)
print(arr)

[-1 -1 -1]
['1 2 3' '4 5 6' '7 8 9']


##### autostrip argument

In [61]:
# autostrip automatically strips the string with whitespaces.
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", dtype=None)
print(arr)
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", dtype=None, autostrip=True)
print(arr)

[('Alice', 90) ('Maggie', 92) ('Drax  ', 68)]
[('Alice', 90) ('Maggie', 92) ('Drax', 68)]


#### names argument

##### Using names from file

In [62]:
# names argument gives names to the columns.
arr = np.genfromtxt("files/students_data_1.csv", delimiter=",", dtype=None, autostrip=True, names=True)
print(arr)
print()

print(arr.dtype)
print()

print(arr['Roll'])
print(arr['Name'])


[(10, 'Rahul', 92, 16, 'A') ( 5, 'Shreya', 91, 16, 'A')
 (29, 'Prem', 72, 17, 'C') (23, 'Het', 83, 16, 'B')]

[('Roll', '<i8'), ('Name', '<U6'), ('Percentage', '<i8'), ('Age', '<i8'), ('Grade', '<U1')]

[10  5 29 23]
['Rahul' 'Shreya' 'Prem' 'Het']


##### Using names from variable

In [63]:
names = "Name, Marks"
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", dtype=None, autostrip=True, names=names)
arr

array([('Alice', 90), ('Maggie', 92), ('Drax', 68)],
      dtype=[('Name', '<U6'), ('Marks', '<i8')])

#### Skipping headers and footers

##### Skipping lines from starting of the file.

In [64]:
# arr = np.genfromtxt("files/numbers_3.txt")
# print(arr)

# Above code will produce an error.

arr = np.genfromtxt("files/numbers_3.txt", skip_header=1)
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


##### Skipping lines from ending of the file.

In [65]:
# arr = np.genfromtxt("files/numbers_4.txt")
# print(arr)

# Above code will produce an error.

arr = np.genfromtxt("files/numbers_4.txt", skip_footer=1)
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


#### Other useful arguments

##### comments argument

Defines which marker is for comments in file.

Default value of it is #.

In [66]:
arr = np.genfromtxt("files/numbers_5.csv", delimiter=",", comments="//")
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

##### usecols argument

Defines which columns should be existed in array.

In [67]:
arr = np.genfromtxt("files/numbers_1.txt", usecols=[0, 2])
arr

array([[1., 3.],
       [4., 6.],
       [7., 9.]])

##### unpack argument

Distributes the columns to variables.

In [68]:
a, b, c = np.genfromtxt("files/numbers_1.txt", unpack=True)
print(a, b, c, sep='\n')

[1. 4. 7.]
[2. 5. 8.]
[3. 6. 9.]


##### converters argument

converts perform given operations while creating array.

In [69]:
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", autostrip=True, dtype=None, converters={0: lambda x: x.upper()})
arr

array([('ALICE', 90), ('MAGGIE', 92), ('DRAX', 68)],
      dtype=[('f0', '<U6'), ('f1', '<i8')])

Use cases of converters : to convert text case, to replace missing values, to create date object for dates, etc.

##### defaultfmt arguments

In [70]:
# By default, names are given as f0, f1, f2,.....
arr = np.genfromtxt("files/numbers_1.txt", dtype=[int, int, int])
print(arr.dtype)

# We can define to give names by using defaultfmt argument.
arr = np.genfromtxt("files/numbers_1.txt", dtype=[int, int, int], defaultfmt="column_%d")
print(arr.dtype)

[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8')]
[('column_0', '<i8'), ('column_1', '<i8'), ('column_2', '<i8')]


#### Missing and Filling values

##### Missing values

Whenever an value is empty is file, it will be considered as a missing value in array.

In [71]:
arr = np.genfromtxt("files/numbers_6.csv", delimiter=",")
print(arr)

#  float     nan
#  int       -1
#  str       ""
#  boolean   False

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [nan  8.  9.]]


##### Filling Values argument

filling_values argument fills the missing values as given.

In [72]:
arr = np.genfromtxt("files/numbers_6.csv", delimiter=",", filling_values=-1)
print(arr)

[[ 1.  2.  3.]
 [ 4. -1.  6.]
 [-1.  8.  9.]]


#### Reading from URL or file object

##### URL

In [73]:
with open("files/numbers_1.txt") as f:
    arr = np.genfromtxt(f)

arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

##### File Object

In [74]:
from io import StringIO

data = StringIO("""1,2,3
    4,5,6
    7,8,9
""")

arr = np.genfromtxt(data, delimiter=",")
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### Validating names

##### replace_space

replace_space argument replaces the spaces in names of columns with given value.

In [75]:
arr = np.genfromtxt("files/students_marks_2.csv", delimiter=",", dtype=['U8', int], names=True, replace_space="_", skip_footer=4)
arr

array([('Het', 80), ('Priya', 86), ('Milan', 67)],
      dtype=[('Student_Name', '<U8'), ('Marks', '<i8')])

##### deletechars

deletechars argument deletes the given characters existing in names of columns.

In [76]:
arr = np.genfromtxt("files/students_marks_2.csv", delimiter=",", dtype=['U8', int], names=True, deletechars="-%", skip_header=4)
arr

array([('Het', 80), ('Priya', 86), ('Milan', 67)],
      dtype=[('StudentName', '<U8'), ('Percentage', '<i8')])

##### case_sensetive

case_sensetive defines what the case should be of columns names of array.

In [77]:
arr = np.genfromtxt("files/students_data_1.csv", delimiter=",", dtype=None, autostrip=True, names=True, case_sensitive=False)
arr.dtype

# case_sensetive=False or case_sensetive='upper' converts case to upper.
# case_sensetive='lower' converts case to lower.
# Default value of case_sensetive is True which remains the case as it is.

dtype([('ROLL', '<i8'), ('NAME', '<U6'), ('PERCENTAGE', '<i8'), ('AGE', '<i8'), ('GRADE', '<U1')])

##### exclude_list

exclude_list don't allow the given values as names of columns of array.

In [78]:
arr = np.genfromtxt("files/students_data_2.csv", delimiter=",", autostrip=True, dtype=None, names=True, excludelist=["Class"])
arr

array([(10, 'Rahul', 92, 16, 11), ( 5, 'Shreya', 91, 16, 12),
       (29, 'Prem', 72, 17, 11), (23, 'Het', 83, 16, 11)],
      dtype=[('Roll', '<i8'), ('Name', '<U6'), ('Percentage', '<i8'), ('Age', '<i8'), ('Class_', '<i8')])

#### Difference between genfromtxt and loadtxt

<pre>
<b><big>
Feature             loadtxt     genfromtxt
</b></big>

Speed                   Faster      Slower

Missing values          Error       Support

Structured arrays       Limited     Excellent

Headers                 Basic       Better support

Difference data types   Limited     Flexible

Converters              Basic       Powerful
</pre>