# Numpy

## Advanced

In [70]:
import numpy as np

### Triogonometric Functions

#### Basic Functions

In [71]:
angle = np.pi / 2
print(np.sin(angle))             # Angle in radian
print(np.cos(angle))
print(np.tan(angle))

1.0
6.123233995736766e-17
1.633123935319537e+16


#### For Arrays

In [72]:
angles = np.array([0, np.pi / 2, np.pi])

print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#### Conversion between degrees & radians

In [73]:
print(np.deg2rad(90))
print(np.rad2deg(np.pi))

1.5707963267948966
180.0


#### Inverse Functions

In [74]:
inverse_angle = 1

print(np.arcsin(inverse_angle))
print(np.arccos(inverse_angle))
print(np.arctan(inverse_angle))

1.5707963267948966
0.0
0.7853981633974483


#### Hyperbolic Functions

In [75]:
print(np.sinh(angle))
print(np.cosh(angle))
print(np.tanh(angle))

print(np.arcsinh(inverse_angle))
print(np.arccosh(inverse_angle))
print(np.arctanh(inverse_angle - 0.1))

2.3012989023072947
2.5091784786580567
0.9171523356672744
0.881373587019543
0.0
1.4722194895832204


### Useful Functions

#### exp

In [76]:
print(np.exp(0))              # Returns exponential value
print(np.exp(1))
print(np.exp(2))

print(np.expm1(0))            # Return e**x - 1
print(np.expm1(1))
print(np.expm1(2))

1.0
2.718281828459045
7.38905609893065
0.0
1.718281828459045
6.38905609893065


In [77]:
arr = np.array([1,2,3,4,5])
print(np.exp(arr))
print(np.expm1(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]


#### log

In [78]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


#### fromfunction

This numpy array creation method applies the given function to all the elements while creating the array.

##### Using def

In [79]:
def sum(x, y):
    return x + y

arr = np.fromfunction(sum, (3, 5), dtype=int)
arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

##### Using lambda

In [80]:
arr = np.fromfunction(lambda x, y: (x+1) * (y+1), (4, 4), dtype=int)
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

#### flat

In [81]:
arr = np.arange(1,11)
for i in arr.flat:               # This lets you to work with each elements indivisually of numpy array.
    print(i)

1
2
3
4
5
6
7
8
9
10


#### expand_dims

In [82]:
# adds another dimension to array
arr = np.array([10, 20, 30])

np.expand_dims(arr, axis=1)

array([[10],
       [20],
       [30]])

### Dimensional Indexing Tools

#### ellipsis (...)

##### 3D array

In [83]:
arr_3D = np.arange(2*3*4).reshape(2,3,4)

print(arr_3D[:, :, 2])
print()
print(arr_3D[..., 2])

[[ 2  6 10]
 [14 18 22]]

[[ 2  6 10]
 [14 18 22]]


##### 4D array

In [84]:
arr_4D = np.arange(2*3*4*5).reshape(2,3,4,5)

print(arr_4D[0, :, :, 2])
print()
print(arr_4D[0, ..., 2])

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


#### newaxis

##### basics

In [85]:
# newaxis adds dimension to the resulting selection
arr = np.arange(1,5)
print(arr, arr.shape, sep='\n')
print()

new_arr_1 = arr[:, np.newaxis]
print(new_arr_1, new_arr_1.shape, sep='\n')
print()

new_arr_2 = arr[np.newaxis, :]
print(new_arr_2, new_arr_2.shape, sep='\n')

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[1 2 3 4]]
(1, 4)


##### newaxis for broadcasting

In [86]:
a = np.array([1, 2, 3])
b = np.array([10, 20])

# a + b will produce an error.
# but we can use newaxis to do broadcasting in these two arrays.

a[:, np.newaxis] + b

array([[11, 21],
       [12, 22],
       [13, 23]])

### -1 in reshaping

In [87]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
arr.reshape(4, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
arr_3D.reshape(2, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [90]:
arr_3D.reshape(4, -1)            # Converted from 3D to 2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Advanced Indexing

#### Basics

##### 1D Arrays

In [91]:
arr = np.array([10,20,30,40,50])

# Advanced Integer Indexing
indices = np.array([0, 2])
print('Advanced Integer Indexing : ', arr[indices])

# Using python list
print('Using python list : ', arr[[0, 2]])

# Repeat indices
print('Repeated indices : ', arr[[0, 2, 2, 3, 0]])

# Negative indices
print('Negative indices : ', arr[[0, -3, 1]])

Advanced Integer Indexing :  [10 30]
Using python list :  [10 30]
Repeated indices :  [10 30 30 40 10]
Negative indices :  [10 30 20]


##### 2D Arrays

In [92]:
arr_2D = np.arange(9).reshape(3,3)

# Selecting rows
print(arr_2D[[0, 2]])
print()

# Spesific element
# Numpy will pair the indices
row = [0]
col = [2]
print(arr_2D[row, col])

rows = [0, 1, 2]
cols = [0, 1, 2]
print(arr_2D[rows, cols])

[[0 1 2]
 [6 7 8]]

[2]
[0 4 8]


##### copy

In [93]:
# Advanced Indexing creates a copy
arr_temp = np.array([10, 20, 30, 40])
x = arr_temp[[0, 2]]
x[0] = 999
print(x, arr_temp, sep='\n')

[999  30]
[10 20 30 40]


#### np.ix_()

In [94]:
# In indexing spesific elements from 2D array, advanced indexing pairs the corresponding indices. But np.ix_() pairs all the indices and make all the combinations.

print('Advanced Indexing : ', arr_2D[rows, cols])
print()
print('np.ix_() : ', arr_2D[np.ix_(rows, cols)], sep='\n')

Advanced Indexing :  [0 4 8]

np.ix_() : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Broadcasting with Advaned Indexing

In [95]:
# When advanced index arrays have the same shape, advanced index arrays have the same shape
# Broadcasting comes in when index arrays have different shapes.

rows = np.array([               # Shape : (2,1)
    [0],
    [1]
])
cols = np.array([0, 2, 1])      # Shape : (3,) -> (1,3) because Numpy treats cols's shape as (1, 3)
print(arr_2D[rows, cols])

# Broadcasting
#
# - dimensions :
#   2 1
#   1 3
#
# - Compare from the right :
#   1 and 3 -> compatible
#   2 and 1 -> compatible
#   Because one of the dimensions is 1, Numpy can expand it.
#   Both becomes (2,3) because Numpy choose max of dimensions - max of right side is 3 and max of left side is 2 so shape becomes (2,3)
#
# - Expand rows
#   [[0],  ->  [[0, 0, 0],
#    [1]        [1, 1, 1]]
#
# - Expand cols
#   [0, 2, 1]  ->  [[0, 2, 1],
#                   [0, 2, 1]]
#
# - Pair the coordinates and get the values.


[[0 2 1]
 [3 5 4]]


#### Combination of basic and advanced indexing

In [96]:
arr = np.arange(20).reshape(4,5)

# Row - 0 and 2
# Col - 1 to 4(excluding)
print(arr[[0, 2], 1:4])


[[ 1  2  3]
 [11 12 13]]


### Field Access

#### Basics

In [97]:
arr = np.array([
    ("Dhvanit", 19, 93),
    ("Het", 18, 81),
    ("Sujal", 21, 60)
], dtype=[
    ("name", "U20"),
    ("age", "i4"),
    ("marks", "i4")
])

print(arr)
print(arr["name"])

print(arr['age'][1])
print(arr[['name', 'marks']])

print(arr.dtype.names)

[('Dhvanit', 19, 93) ('Het', 18, 81) ('Sujal', 21, 60)]
['Dhvanit' 'Het' 'Sujal']
18
[('Dhvanit', 93) ('Het', 81) ('Sujal', 60)]
('name', 'age', 'marks')


#### View

In [98]:
# Field access creates a view.
marks = arr['marks']
marks[1] = 100

print(marks, arr, sep='\n')

[ 93 100  60]
[('Dhvanit', 19,  93) ('Het', 18, 100) ('Sujal', 21,  60)]


#### Multidimensional structured arrays

In [99]:
arr_2D = np.zeros((2, 3), dtype=[
    ("x", "i4"),
    ("y", "f4")
])
print(arr_2D['x'], arr_2D['y'], sep='\n')

[[0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]]


### Variable numbers of indices withing programs

#### Basics

In [100]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

index1 = (2,)
index2 = (1, 2)
index3 = (1, 1, 1)

print(arr1[index1])
print(arr2[index2])
print(arr3[index3])

30
60
8


#### Dynamic indices

##### First element

In [101]:
arr = np.arange(20).reshape(4,5)

index = (0,) * arr.ndim

print(arr[index])

0


##### Last dimension

In [102]:
arr = np.arange(120).reshape(2,3,4,-1)

index = (slice(None),) * (arr.ndim - 1) + (-1,)

print(arr[index])       # equivalent to arr[:,:,:,-1] or arr[...,-1]

[[[  4   9  14  19]
  [ 24  29  34  39]
  [ 44  49  54  59]]

 [[ 64  69  74  79]
  [ 84  89  94  99]
  [104 109 114 119]]]


#### Function example

In [103]:
def set_first_element(arr, el):
    index = (0,) * arr.ndim
    arr[index] = el

def access_first_element(arr):
    index = (0,) * arr.ndim
    return arr[index]

In [104]:
arr1 = np.arange(5)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(30).reshape(2,3,-1)
arr4 = np.arange(120).reshape(2,3,4,-1)
arr5 = np.arange(300).reshape(1,2,3,5,-1)

set_first_element(arr1, 10)
set_first_element(arr2, 5)
set_first_element(arr3, 17)
set_first_element(arr4, -5)
set_first_element(arr5, 0)

In [105]:
print(access_first_element(arr1), access_first_element(arr2), access_first_element(arr3), access_first_element(arr4), access_first_element(arr5), sep='\n')

10
5
17
-5
0


#### np.s_ and np.index_exp

In [106]:
# It's used when we need to construct slices programmatically.
arr = np.arange(20).reshape(4,5)

index = np.s_[1:3, :2]

print(arr[index])

[[ 5  6]
 [10 11]]


In [107]:
index = np.index_exp[1:3, :2]

print(arr[index])

[[ 5  6]
 [10 11]]
