# Numpy

## Advanced

In [58]:
import numpy as np

### Triogonometric Functions

#### Basic Functions

In [59]:
angle = np.pi / 2
print(np.sin(angle))             # Angle in radian
print(np.cos(angle))
print(np.tan(angle))

1.0
6.123233995736766e-17
1.633123935319537e+16


#### For Arrays

In [60]:
angles = np.array([0, np.pi / 2, np.pi])

print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#### Conversion between degrees & radians

In [61]:
print(np.deg2rad(90))
print(np.rad2deg(np.pi))

1.5707963267948966
180.0


#### Inverse Functions

In [62]:
inverse_angle = 1

print(np.arcsin(inverse_angle))
print(np.arccos(inverse_angle))
print(np.arctan(inverse_angle))

1.5707963267948966
0.0
0.7853981633974483


#### Hyperbolic Functions

In [63]:
print(np.sinh(angle))
print(np.cosh(angle))
print(np.tanh(angle))

print(np.arcsinh(inverse_angle))
print(np.arccosh(inverse_angle))
print(np.arctanh(inverse_angle - 0.1))

2.3012989023072947
2.5091784786580567
0.9171523356672744
0.881373587019543
0.0
1.4722194895832204


### Useful Functions

#### exp

In [64]:
print(np.exp(0))              # Returns exponential value
print(np.exp(1))
print(np.exp(2))

print(np.expm1(0))            # Return e**x - 1
print(np.expm1(1))
print(np.expm1(2))

1.0
2.718281828459045
7.38905609893065
0.0
1.718281828459045
6.38905609893065


In [65]:
arr = np.array([1,2,3,4,5])
print(np.exp(arr))
print(np.expm1(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]


#### log

In [66]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


#### fromfunction

##### Using def

In [67]:
def sum(x, y):
    return x + y

arr = np.fromfunction(sum, (3, 5), dtype=int)
arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

##### Using lambda

In [68]:
arr = np.fromfunction(lambda x, y: (x+1) * (y+1), (4, 4), dtype=int)
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

#### flat

In [69]:
arr = np.arange(1,11)
for i in arr.flat:               # This lets you to work with each elements indivisually of numpy array.
    print(i)

1
2
3
4
5
6
7
8
9
10


#### ellipsis (...)

##### 3D array

In [70]:
arr_3D = np.arange(2*3*4).reshape(2,3,4)

print(arr_3D[:, :, 2])
print()
print(arr_3D[..., 2])

[[ 2  6 10]
 [14 18 22]]

[[ 2  6 10]
 [14 18 22]]


##### 4D array

In [71]:
arr_4D = np.arange(2*3*4*5).reshape(2,3,4,5)

print(arr_4D[0, :, :, 2])
print()
print(arr_4D[0, ..., 2])

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


#### -1 in reshaping

In [72]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
arr.reshape(4, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [74]:
arr_3D.reshape(2, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [75]:
arr_3D.reshape(4, -1)            # Converted from 3D to 2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])