# Numpy

## Advanced

In [37]:
import numpy as np

### Triogonometric Functions

#### Basic Functions

In [38]:
angle = np.pi / 2
print(np.sin(angle))             # Angle in radian
print(np.cos(angle))
print(np.tan(angle))

1.0
6.123233995736766e-17
1.633123935319537e+16


#### For Arrays

In [39]:
angles = np.array([0, np.pi / 2, np.pi])

print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


#### Conversion between degrees & radians

In [40]:
print(np.deg2rad(90))
print(np.rad2deg(np.pi))

1.5707963267948966
180.0


#### Inverse Functions

In [41]:
inverse_angle = 1

print(np.arcsin(inverse_angle))
print(np.arccos(inverse_angle))
print(np.arctan(inverse_angle))

1.5707963267948966
0.0
0.7853981633974483


#### Hyperbolic Functions

In [42]:
print(np.sinh(angle))
print(np.cosh(angle))
print(np.tanh(angle))

print(np.arcsinh(inverse_angle))
print(np.arccosh(inverse_angle))
print(np.arctanh(inverse_angle - 0.1))

2.3012989023072947
2.5091784786580567
0.9171523356672744
0.881373587019543
0.0
1.4722194895832204


### Useful Functions

#### exp

In [43]:
print(np.exp(0))              # Returns exponential value
print(np.exp(1))
print(np.exp(2))

print(np.expm1(0))            # Return e**x - 1
print(np.expm1(1))
print(np.expm1(2))

1.0
2.718281828459045
7.38905609893065
0.0
1.718281828459045
6.38905609893065


In [44]:
arr = np.array([1,2,3,4,5])
print(np.exp(arr))
print(np.expm1(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  1.71828183   6.3890561   19.08553692  53.59815003 147.4131591 ]


#### log

In [45]:
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


#### fromfunction

This numpy array creation method applies the given function to all the elements while creating the array.

##### Using def

In [46]:
def sum(x, y):
    return x + y

arr = np.fromfunction(sum, (3, 5), dtype=int)
arr

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

##### Using lambda

In [47]:
arr = np.fromfunction(lambda x, y: (x+1) * (y+1), (4, 4), dtype=int)
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

#### flat

In [48]:
arr = np.arange(1,11)
for i in arr.flat:               # This lets you to work with each elements indivisually of numpy array.
    print(i)

1
2
3
4
5
6
7
8
9
10


#### expand_dims

In [49]:
# adds another dimension to array
arr = np.array([10, 20, 30])

np.expand_dims(arr, axis=1)

array([[10],
       [20],
       [30]])

### Dimensional Indexing Tools

#### ellipsis (...)

##### 3D array

In [50]:
arr_3D = np.arange(2*3*4).reshape(2,3,4)

print(arr_3D[:, :, 2])
print()
print(arr_3D[..., 2])

[[ 2  6 10]
 [14 18 22]]

[[ 2  6 10]
 [14 18 22]]


##### 4D array

In [51]:
arr_4D = np.arange(2*3*4*5).reshape(2,3,4,5)

print(arr_4D[0, :, :, 2])
print()
print(arr_4D[0, ..., 2])

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]

[[ 2  7 12 17]
 [22 27 32 37]
 [42 47 52 57]]


#### newaxis

##### basics

In [52]:
# newaxis adds dimension to the resulting selection
arr = np.arange(1,5)
print(arr, arr.shape, sep='\n')
print()

new_arr_1 = arr[:, np.newaxis]
print(new_arr_1, new_arr_1.shape, sep='\n')
print()

new_arr_2 = arr[np.newaxis, :]
print(new_arr_2, new_arr_2.shape, sep='\n')

[1 2 3 4]
(4,)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[1 2 3 4]]
(1, 4)


##### newaxis for broadcasting

In [53]:
a = np.array([1, 2, 3])
b = np.array([10, 20])

# a + b will produce an error.
# but we can use newaxis to do broadcasting in these two arrays.

a[:, np.newaxis] + b

array([[11, 21],
       [12, 22],
       [13, 23]])

### -1 in reshaping

In [54]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
arr.reshape(4, -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [56]:
arr_3D.reshape(2, -1, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [57]:
arr_3D.reshape(4, -1)            # Converted from 3D to 2D

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### Advanced Indexing

#### Basics

##### 1D Arrays

In [79]:
arr = np.array([10,20,30,40,50])

# Advanced Integer Indexing
indices = np.array([0, 2])
print('Advanced Integer Indexing : ', arr[indices])

# Using python list
print('Using python list : ', arr[[0, 2]])

# Repeat indices
print('Repeated indices : ', arr[[0, 2, 2, 3, 0]])

# Negative indices
print('Negative indices : ', arr[[0, -3, 1]])

Advanced Integer Indexing :  [10 30]
Using python list :  [10 30]
Repeated indices :  [10 30 30 40 10]
Negative indices :  [10 30 20]


##### 2D Arrays

In [80]:
arr_2D = np.arange(9).reshape(3,3)

# Selecting rows
print(arr_2D[[0, 2]])
print()

# Spesific element
# Numpy will pair the indices
row = [0]
col = [2]
print(arr_2D[row, col])

rows = [0, 1, 2]
cols = [0, 1, 2]
print(arr_2D[rows, cols])
print()

# Advanced Indexing creates a copy
arr_temp = np.array([10, 20, 30, 40])
x = arr_temp[[0, 2]]
x[0] = 999
print(x, arr_temp, sep='\n')

[[0 1 2]
 [6 7 8]]

[2]
[0 4 8]

[999  30]
[10 20 30 40]


#### np.ix_()

In [81]:
# In indexing spesific elements from 2D array, advanced indexing pairs the corresponding indices. But np.ix_() pairs all the indices and make all the combinations.

print('Advanced Indexing : ', arr_2D[rows, cols])
print()
print('np.ix_() : ', arr_2D[np.ix_(rows, cols)], sep='\n')

Advanced Indexing :  [0 4 8]

np.ix_() : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Broadcasting with Advaned Indexing

In [82]:
# When advanced index arrays have the same shape, advanced index arrays have the same shape
# Broadcasting comes in when index arrays have different shapes.

rows = np.array([               # Shape : (2,1)
    [0],
    [1]
])
cols = np.array([0, 2, 1])      # Shape : (3,) -> (1,3) because Numpy treats cols's shape as (1, 3)
print(arr_2D[rows, cols])

# Broadcasting
#
# - dimensions :
#   2 1
#   1 3
#
# - Compare from the right :
#   1 and 3 -> compatible
#   2 and 1 -> compatible
#   Because one of the dimensions is 1, Numpy can expand it.
#   Both becomes (2,3) because Numpy choose max of dimensions - max of right side is 3 and max of left side is 2 so shape becomes (2,3)
#
# - Expand rows
#   [[0],  ->  [[0, 0, 0],
#    [1]        [1, 1, 1]]
#
# - Expand cols
#   [0, 2, 1]  ->  [[0, 2, 1],
#                   [0, 2, 1]]
#
# - Pair the coordinates and get the values.


[[0 2 1]
 [3 5 4]]


#### Combination of basic and advanced indexing

In [83]:
arr = np.arange(20).reshape(4,5)

# Row - 0 and 2
# Col - 1 to 4(excluding)
print(arr[[0, 2], 1:4])


[[ 1  2  3]
 [11 12 13]]
