# Numpy

## Basics

In [10]:
import numpy as np

### Basic Array Creation

In [11]:
arr = np.array([1, 5, 10, 100, 240])
arr

array([  1,   5,  10, 100, 240])

In [12]:
arr = np.array([1, 5, 8.5, "hello"])
print(arr)
arr = np.array([1, 5, 8.5])
print(arr)

['1' '5' '8.5' 'hello']
[1.  5.  8.5]


In [13]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9],])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Generic Funtion

In [15]:
arr = np.arange(5, 40, 5)
arr

array([ 5, 10, 15, 20, 25, 30, 35])

In [17]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
arr = np.linspace(10,20,6)
arr

array([10., 12., 14., 16., 18., 20.])

### Random Generic Function

In [ ]:
arr = np.random.rand(10)            # Between 0 to 1 - called normalization
arr

array([0.19123741, 0.44427019, 0.21056543, 0.21338817, 0.05183676,
       0.9039253 , 0.77528701, 0.29033633, 0.19700074, 0.05946257])

In [ ]:
arr = np.random.randn(10)            # Between -3 to 3 - called standardization
arr

array([-0.11593044,  2.15266928, -0.00831079,  0.00587203, -1.32707403,
       -0.75452088, -0.10459679, -0.48189503, -0.02973462, -0.48168984])

In [28]:
arr = np.random.randint(0,10,10)
arr

array([8, 7, 2, 2, 0, 0, 9, 4, 4, 7], dtype=int32)

### Array Attributes