# Numpy

## Basics

In [1]:
import numpy as np

### Arrays

#### Basic Array Creation

In [2]:
arr = np.array([1, 5, 10, 100, 240])
arr

array([  1,   5,  10, 100, 240])

In [3]:
arr = np.array([1, 5, 8.5, "hello"])
print(arr)

arr = np.array([1, 5, 8.5])
print(arr)

['1' '5' '8.5' 'hello']
[1.  5.  8.5]


In [4]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9],])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generic Funtion

In [5]:
arr = np.arange(5, 40, 5)
arr

array([ 5, 10, 15, 20, 25, 30, 35])

In [6]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr = np.empty((2,3))
arr

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [9]:
arr = np.linspace(10,20,6)
arr

array([10., 12., 14., 16., 18., 20.])

#### Random Generic Function

In [10]:
arr = np.random.rand(10)            # Between 0 to 1 - called normalization
arr

array([0.50980187, 0.411479  , 0.9637916 , 0.9993416 , 0.17753964,
       0.96509038, 0.5120356 , 0.71625383, 0.13570316, 0.69822439])

In [11]:
arr = np.random.randn(10)            # Between -3 to 3 - called standardization
arr

array([ 1.02941222, -1.61031116, -0.81969903, -0.89597216,  1.43055308,
       -0.14950927, -1.22401175, -1.22723025,  0.45668074,  1.81069053])

In [12]:
arr = np.random.randint(0,10,10)
arr

array([0, 8, 9, 0, 2, 1, 1, 0, 5, 3], dtype=int32)

#### Array Attributes

In [13]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr.shape

(3, 3)

In [15]:
arr.size

9

In [16]:
arr.dtype

dtype('int64')

In [17]:
arr.ndim

2

In [ ]:
# base attribute prints None if array owns it's data or is a copy of another array and prints array if it's a view of another array.
print(arr.base)

None


#### Array Methods

In [18]:
arr.min()

np.int64(1)

In [19]:
arr.max()

np.int64(9)

In [20]:
arr.sum()

np.int64(45)

In [21]:
np.sum(arr, axis=0)            # Columns

array([12, 15, 18])

In [22]:
arr.mean()

np.float64(5.0)

In [23]:
arr.std()

np.float64(2.581988897471611)

In [24]:
arr.argmax()

np.int64(8)

In [25]:
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [26]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [27]:
arr = arr.reshape(6,5)           # process to reshaping an array is called resizing.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Array Indexing

#### Vector

In [28]:
arr = np.arange(11,21)
print(arr)
print()

print(arr[5])      # Single element
print(arr[2:7:2])  # Range

[11 12 13 14 15 16 17 18 19 20]

16
[13 15 17]


#### Matrix

In [29]:
arr = np.arange(1,31).reshape(6,5)
print(arr)
print()

print('Row : ', arr[5])           # Row
print('Single element : ', arr[5,2])         # Single element
print('Range : ', arr[1:3,:4], sep='\n')      # Range
print('Column : ', arr[:,3])         # Column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Row :  [26 27 28 29 30]
Single element :  28
Range : 
[[ 6  7  8  9]
 [11 12 13 14]]
Column :  [ 4  9 14 19 24 29]


#### Boolean Indexing

In [30]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
boolean_index = arr % 2 == 0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [32]:
ever_arr = arr[boolean_index]
ever_arr

array([12, 14, 16, 18, 20])

### Operations

#### Aerithmetic Operations

In [33]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [34]:
a1 + a2                # All other aerithmetic operations also work like this.

array([ 7,  9, 11, 13, 15])

In [35]:
m1 = np.arange(1,11).reshape(2,5)
m2 = np.arange(11,21).reshape(2,5)

In [36]:
m1 * m2                   # All other aerithmetic operations also work like this.

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

#### Broadcasting

In [37]:
a1 + 10

array([11, 12, 13, 14, 15])

In [38]:
m1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Deep copy, Shallow copy, & Assignment

In [39]:
a = np.arange(1,11)

##### Deep copy

In [40]:
deep_copy = a.copy()
deep_copy += 10

print(deep_copy)
print(a)

[11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]


##### Shallow copy

In [41]:
shallow_copy = a.view()
shallow_copy += 10

print(shallow_copy)
print(a)

print(shallow_copy is a)

[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
False


##### Assignment

In [42]:
assigned_object = a
assigned_object += 100

print(assigned_object)
print(a)

print(assigned_object is a)

[111 112 113 114 115 116 117 118 119 120]
[111 112 113 114 115 116 117 118 119 120]
True


#### Matrix Operations

In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [44]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [45]:
A * B

array([[ 5, 12],
       [21, 32]])

In [46]:
np.dot(A, B)                  # A @ B will also work like this.

array([[19, 22],
       [43, 50]])

In [47]:
A.T

array([[1, 3],
       [2, 4]])

#### Advanced Array Manipulation

##### Stacking Array

In [48]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [49]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

##### Splitting Array

In [52]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [55]:
# Splitting into parts which can't be devided by rows or columns will generate the error.
# ex :  arr => 4 x 4
#       You can't split arr into 3 parts  