# Numpy

## Basics

In [2]:
import numpy as np

### Arrays

#### Basic Array Creation

In [2]:
arr = np.array([1, 5, 10, 100, 240])
arr

array([  1,   5,  10, 100, 240])

In [3]:
arr = np.array([1, 5, 8.5, "hello"])
print(arr)
arr = np.array([1, 5, 8.5])
print(arr)

['1' '5' '8.5' 'hello']
[1.  5.  8.5]


In [4]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9],])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generic Funtion

In [5]:
arr = np.arange(5, 40, 5)
arr

array([ 5, 10, 15, 20, 25, 30, 35])

In [6]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
arr = np.linspace(10,20,6)
arr

array([10., 12., 14., 16., 18., 20.])

#### Random Generic Function

In [9]:
arr = np.random.rand(10)            # Between 0 to 1 - called normalization
arr

array([0.40778063, 0.71950715, 0.32062183, 0.51411049, 0.2279985 ,
       0.19421694, 0.28482127, 0.49463497, 0.35725815, 0.17844677])

In [10]:
arr = np.random.randn(10)            # Between -3 to 3 - called standardization
arr

array([-0.78123373, -0.13377067, -0.09490063,  0.0628024 , -0.28886992,
       -2.81119795,  0.15538365, -0.50872673,  0.39574387,  0.83931138])

In [11]:
arr = np.random.randint(0,10,10)
arr

array([2, 8, 7, 8, 5, 4, 6, 9, 0, 9], dtype=int32)

#### Array Attributes

In [3]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr.shape

(3, 3)

In [14]:
arr.size

9

In [15]:
arr.dtype

dtype('int64')

#### Array Methods

In [16]:
arr.min()

np.int64(1)

In [17]:
arr.max()

np.int64(9)

In [18]:
arr.sum()

np.int64(45)

In [21]:
np.sum(arr, axis=0)            # Columns

array([12, 15, 18])

In [22]:
arr.mean()

np.float64(5.0)

In [23]:
arr.std()

np.float64(2.581988897471611)

In [4]:
arr.argmax()

np.int64(8)

In [5]:
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [7]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)           # process to reshaping an array is called resizing.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Array Indexing