# Numpy

## Basics

In [70]:
import numpy as np

### Arrays

#### Basic Array Creation

In [71]:
arr = np.array([1, 5, 10, 100, 240])
arr

array([  1,   5,  10, 100, 240])

In [ ]:
arr = np.array([1, 5, 8.5, "hello"])
print(arr)

arr = np.array([1, 5, 8.5])
print(arr)

['1' '5' '8.5' 'hello']
[1.  5.  8.5]


In [73]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9],])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Array Generic Funtion

In [74]:
arr = np.arange(5, 40, 5)
arr

array([ 5, 10, 15, 20, 25, 30, 35])

In [75]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [77]:
arr = np.empty((2,3))
arr

array([[10., 12., 14.],
       [16., 18., 20.]])

In [78]:
arr = np.linspace(10,20,6)
arr

array([10., 12., 14., 16., 18., 20.])

#### Random Generic Function

In [79]:
arr = np.random.rand(10)            # Between 0 to 1 - called normalization
arr

array([0.83379873, 0.87724597, 0.22632876, 0.78948323, 0.64155348,
       0.1053078 , 0.74731943, 0.10199693, 0.33434   , 0.44881351])

In [80]:
arr = np.random.randn(10)            # Between -3 to 3 - called standardization
arr

array([-7.24464262e-04, -1.14813074e+00, -3.24798080e-01,  1.91514929e-01,
        9.40508041e-01, -1.99152913e+00,  7.48723158e-01,  1.43901048e+00,
       -2.19738995e+00, -5.90991444e-01])

In [81]:
arr = np.random.randint(0,10,10)
arr

array([9, 1, 1, 4, 9, 3, 8, 4, 3, 0], dtype=int32)

#### Array Attributes

In [82]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr.shape

(3, 3)

In [84]:
arr.size

9

In [85]:
arr.dtype

dtype('int64')

In [86]:
arr.ndim

2

#### Array Methods

In [87]:
arr.min()

np.int64(1)

In [88]:
arr.max()

np.int64(9)

In [89]:
arr.sum()

np.int64(45)

In [90]:
np.sum(arr, axis=0)            # Columns

array([12, 15, 18])

In [91]:
arr.mean()

np.float64(5.0)

In [92]:
arr.std()

np.float64(2.581988897471611)

In [93]:
arr.argmax()

np.int64(8)

In [94]:
arr.argmin()

np.int64(0)

#### Reshaping and Resizing

In [95]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [96]:
arr = arr.reshape(6,5)           # process to reshaping an array is called resizing.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Array Indexing

#### Vector

In [97]:
arr = np.arange(11,21)
print(arr)
print()

print(arr[5])      # Single element
print(arr[2:7:2])  # Range

[11 12 13 14 15 16 17 18 19 20]

16
[13 15 17]


#### Matrix

In [98]:
arr = np.arange(1,31).reshape(6,5)
print(arr)
print()

print('Row : ', arr[5])           # Row
print('Single element : ', arr[5,2])         # Single element
print('Range : ', arr[1:3,:4], sep='\n')      # Range
print('Column : ', arr[:,3])         # Column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Row :  [26 27 28 29 30]
Single element :  28
Range : 
[[ 6  7  8  9]
 [11 12 13 14]]
Column :  [ 4  9 14 19 24 29]


#### Boolean Indexing

In [99]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [100]:
boolean_index = arr % 2 == 0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [101]:
ever_arr = arr[boolean_index]
ever_arr

array([12, 14, 16, 18, 20])

### Operations

#### Aerithmetic Operations

In [102]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [103]:
a1 + a2                # All other aerithmetic operations also work like this.

array([ 7,  9, 11, 13, 15])

In [104]:
m1 = np.arange(1,11).reshape(2,5)
m2 = np.arange(11,21).reshape(2,5)

In [105]:
m1 * m2                   # All other aerithmetic operations also work like this.

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

#### Broadcasting

In [106]:
a1 + 10

array([11, 12, 13, 14, 15])

In [107]:
m1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### Deep copy, Shallow copy, & Assignment

In [108]:
a = np.arange(1,11)

##### Deep copy

In [109]:
deep_copy = a.copy()
deep_copy += 10

print(deep_copy)
print(a)

[11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]


##### Shallow copy

In [110]:
shallow_copy = a.view()
shallow_copy += 10

print(shallow_copy)
print(a)

print(shallow_copy is a)

[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
False


##### Assignment

In [111]:
assigned_object = a
assigned_object += 100

print(assigned_object)
print(a)

print(assigned_object is a)

[111 112 113 114 115 116 117 118 119 120]
[111 112 113 114 115 116 117 118 119 120]
True


#### Matrix Operations

In [112]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [113]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [114]:
A * B

array([[ 5, 12],
       [21, 32]])

In [115]:
np.dot(A, B)                  # A @ B will also work like this.

array([[19, 22],
       [43, 50]])

In [116]:
A.T

array([[1, 3],
       [2, 4]])

#### Advanced Array Manipulation

##### Stacking Array

In [117]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [118]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [119]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

##### Splitting Array

In [121]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [123]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [124]:
# Splitting into parts which can't be devided by rows or columns will generate the error.
# ex :  arr => 4 x 4
#       You can't split arr into 3 parts  