# Numpy

## Exercise

In [60]:
import numpy as np

### Valid Sudoku

In [61]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [62]:
is_sudoku_valid = True

for i in range(9):
    if not is_sudoku_valid:
        break

    if s[i].sum() != 45 or s[:,i].sum() != 45:
        is_sudoku_valid = False
        break

    if i in [0, 3, 6]:
        for j in range(0,8,3):
            if s[i:i+3, j:j+3].sum() != 45:
                is_sudoku_valid = False
                break


if is_sudoku_valid:
    print("Valid Sudoku")
else:
    print("Invalid Sudoku")

Valid Sudoku


### Students data

In [63]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#### Task

##### Answer below questions
- Get the shape of the matrix.
- Find the average age of students.
- Extract Math marks of all students.
- Find the highest Science mark.
- Get details of the student who scored more than 90 in Math.
- Increase Math marks of all students by 5.
- Find how many students are younger than 19.
- Calculate the average marks in each subject (column-wise mean).
- Get data of students who scored at least 80 in both subjects.
- Replace all Science marks < 75 with 0.

#### Implementation

##### Shape

In [64]:
data.shape

(5, 3)

##### Average age

In [65]:
data[:,0].mean()

np.float64(18.4)

##### Maths marks of all students

In [66]:
data[:,1]

array([85, 92, 76, 65, 90])

##### Highest Science marks

In [67]:
data[:,2].max()

np.int64(95)

##### Student details achieving more than 90 marks in Maths

In [68]:
boolean_maths_marks = data[:,1] > 90
data[boolean_maths_marks]

array([[19, 92, 88]])

##### Increase all students Maths' marks by 5

In [69]:
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

##### Total number of students younger than 19

In [70]:
boolean_age = data[:,0] < 19
data[boolean_age][:,0].size

3

##### Average marks in each subjects

In [71]:
np.mean(data[:,1:], axis=0)

array([86.6, 83.2])

##### Students details scored 80 in both subjects

In [72]:
boolean_score_maths = data[:,1] >= 80
boolean_score_science = data[:,2] >= 80
data[boolean_score_maths & boolean_score_science]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

##### Replace Science marks with 0 where less than 75

In [74]:
boolean_science_marks = data[:,2] < 75
data[:,2][boolean_science_marks] = 0

data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])