# Numpy

## I/O in Numpy

In [2]:
import numpy as np

### Reading from files

#### Creating array using file data

In [3]:
# genfromtxt will convert file's data to numpy array.
arr = np.genfromtxt("files/numbers_1.txt")
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [4]:
# delimeter defines which seperator is used in file.
arr = np.genfromtxt("files/numbers_2.csv", delimiter=",")
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### Datatype

In [5]:
# dtype converts datatype to given datatype.
# Default datatype is float
arr = np.genfromtxt("files/numbers_1.txt", delimiter=",", dtype=int)
print(arr)
arr = np.genfromtxt("files/numbers_1.txt", delimiter=",", dtype=str)
print(arr)

[-1 -1 -1]
['1 2 3' '4 5 6' '7 8 9']


#### autostrip argument

In [6]:
# autostrip automatically strips the string with whitespaces.
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", dtype=None)
print(arr)
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", dtype=None, autostrip=True)
print(arr)

[('Alice', 90) ('Maggie', 92) ('Drax  ', 68)]
[('Alice', 90) ('Maggie', 92) ('Drax', 68)]


### Skipping headers and footers

#### Skipping lines from starting of the file.

In [7]:
# arr = np.genfromtxt("files/numbers_3.txt")
# print(arr)

# Above code will produce an error.

arr = np.genfromtxt("files/numbers_3.txt", skip_header=1)
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


#### Skipping lines from ending of the file.

In [8]:
# arr = np.genfromtxt("files/numbers_4.txt")
# print(arr)

# Above code will produce an error.

arr = np.genfromtxt("files/numbers_4.txt", skip_footer=1)
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


### names argument

#### Using names from file

In [9]:
# names argument gives names to the columns.
arr = np.genfromtxt("files/students_data_1.csv", delimiter=",", dtype=None, autostrip=True, names=True)
print(arr)
print()

print(arr.dtype)
print()

print(arr['Roll'])
print(arr['Name'])


[(10, 'Rahul', 92, 16, 'A') ( 5, 'Shreya', 91, 16, 'A')
 (29, 'Prem', 72, 17, 'C') (23, 'Het', 83, 16, 'B')]

[('Roll', '<i8'), ('Name', '<U6'), ('Percentage', '<i8'), ('Age', '<i8'), ('Grade', '<U1')]

[10  5 29 23]
['Rahul' 'Shreya' 'Prem' 'Het']


#### Using names from variable

In [10]:
names = "Name, Marks"
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", dtype=None, autostrip=True, names=names)
arr

array([('Alice', 90), ('Maggie', 92), ('Drax', 68)],
      dtype=[('Name', '<U6'), ('Marks', '<i8')])

#### Validating names

##### replace_space

replace_space argument replaces the spaces in names of columns with given value.

In [11]:
arr = np.genfromtxt("files/students_marks_2.csv", delimiter=",", dtype=['U8', int], names=True, replace_space="_", skip_footer=4)
arr

array([('Het', 80), ('Priya', 86), ('Milan', 67)],
      dtype=[('Student_Name', '<U8'), ('Marks', '<i8')])

##### deletechars

deletechars argument deletes the given characters existing in names of columns.

In [12]:
arr = np.genfromtxt("files/students_marks_2.csv", delimiter=",", dtype=['U8', int], names=True, deletechars="-%", skip_header=4)
arr

array([('Het', 80), ('Priya', 86), ('Milan', 67)],
      dtype=[('StudentName', '<U8'), ('Percentage', '<i8')])

##### case_sensetive

case_sensetive defines what the case should be of columns names of array.

In [13]:
arr = np.genfromtxt("files/students_data_1.csv", delimiter=",", dtype=None, autostrip=True, names=True, case_sensitive=False)
arr.dtype

# case_sensetive=False or case_sensetive='upper' converts case to upper.
# case_sensetive='lower' converts case to lower.
# Default value of case_sensetive is True which remains the case as it is.

dtype([('ROLL', '<i8'), ('NAME', '<U6'), ('PERCENTAGE', '<i8'), ('AGE', '<i8'), ('GRADE', '<U1')])

##### exclude_list

exclude_list don't allow the given values as names of columns of array.

In [14]:
arr = np.genfromtxt("files/students_data_2.csv", delimiter=",", autostrip=True, dtype=None, names=True, excludelist=["Class"])
arr

array([(10, 'Rahul', 92, 16, 11), ( 5, 'Shreya', 91, 16, 12),
       (29, 'Prem', 72, 17, 11), (23, 'Het', 83, 16, 11)],
      dtype=[('Roll', '<i8'), ('Name', '<U6'), ('Percentage', '<i8'), ('Age', '<i8'), ('Class_', '<i8')])

### Other useful arguments

#### comments argument

Defines which marker is for comments in file.

Default value of it is #.

In [15]:
arr = np.genfromtxt("files/numbers_5.csv", delimiter=",", comments="//")
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

#### usecols argument

Defines which columns should be existed in array.

In [16]:
arr = np.genfromtxt("files/numbers_1.txt", usecols=[0, 2])
arr

array([[1., 3.],
       [4., 6.],
       [7., 9.]])

#### unpack argument

Distributes the columns to variables.

In [17]:
a, b, c = np.genfromtxt("files/numbers_1.txt", unpack=True)
print(a, b, c, sep='\n')

[1. 4. 7.]
[2. 5. 8.]
[3. 6. 9.]


#### converters argument

converts perform given operations while creating array.

In [18]:
arr = np.genfromtxt("files/students_marks_1.csv", delimiter=",", autostrip=True, dtype=None, converters={0: lambda x: x.upper()})
arr

array([('ALICE', 90), ('MAGGIE', 92), ('DRAX', 68)],
      dtype=[('f0', '<U6'), ('f1', '<i8')])

Use cases of converters : to convert text case, to replace missing values, to create date object for dates, etc.

#### defaultfmt arguments

In [19]:
# By default, names are given as f0, f1, f2,.....
arr = np.genfromtxt("files/numbers_1.txt", dtype=[int, int, int])
print(arr.dtype)

# We can define to give names by using defaultfmt argument.
arr = np.genfromtxt("files/numbers_1.txt", dtype=[int, int, int], defaultfmt="column_%d")
print(arr.dtype)

[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8')]
[('column_0', '<i8'), ('column_1', '<i8'), ('column_2', '<i8')]


### Missing and Filling values

#### Missing values

Whenever an value is empty is file, it will be considered as a missing value in array.

In [20]:
arr = np.genfromtxt("files/numbers_6.csv", delimiter=",")
print(arr)

#  float     nan
#  int       -1
#  str       ""
#  boolean   False

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [nan  8.  9.]]


#### Filling Values

filling_values argument fills the missing values as given.

In [21]:
arr = np.genfromtxt("files/numbers_6.csv", delimiter=",", filling_values=-1)
print(arr)

[[ 1.  2.  3.]
 [ 4. -1.  6.]
 [-1.  8.  9.]]


### Reading from URL or file object

#### URL

In [22]:
with open("files/numbers_1.txt") as f:
    arr = np.genfromtxt(f)

arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### File Object

In [23]:
from io import StringIO

data = StringIO("""1,2,3
    4,5,6
    7,8,9
""")

arr = np.genfromtxt(data, delimiter=",")
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

### Difference between genfromtxt and loadtxt

<pre>
<b><big>
Feature             loadtxt     genfromtxt
</b></big>

Speed                   Faster      Slower

Missing values          Error       Support

Structured arrays       Limited     Excellent

Headers                 Basic       Better support

Difference data types   Limited     Flexible

Converters              Basic       Powerful
</pre>